include: package:very_good_analysis/analysis_options.3.0.1.yaml
analyzer:
  exclude:
    - '**.g.dart'
    - '**.freezed.dart'

linter:
  rules:
    public_member_api_docs: false
    flutter_style_todos: false